'use strict';
const router = require('express').Router();
const db = require('../database');
const { requireAuth } = require('../middleware/auth');

const VALID_STATUSES = new Set(['pending', 'closed', 'dead', 'vehicle_changed']);

function labelDealType(type) {
  return {
    we_finance: 'We Finance',
    bhph: 'BHPH',
    they_finance: 'They Finance',
    cash: 'Cash',
  }[type] || 'Deal';
}

function dealerEmail(req) {
  return req.user?.email || '';
}

function dealSelect() {
  return `
    SELECT
      d.*,
      c.first_name, c.last_name, c.phone, c.email,
      u.year, u.make, u.model, u.vin,
      (
        SELECT COUNT(*) FROM documents docs
        WHERE docs.deal_id = d.id AND docs.status = 'missing'
      ) AS missing_docs,
      (
        SELECT a.action FROM activity_logs a
        WHERE a.entity_type = 'deal' AND a.entity_id = d.id
        ORDER BY a.created_at DESC LIMIT 1
      ) AS last_activity
    FROM deals d
    LEFT JOIN customers c ON c.id = d.customer_id
    LEFT JOIN units u ON u.id = d.unit_id
    WHERE d.dealership_id = ?
  `;
}

function enrichDeal(row) {
  const customer_name = [row.first_name, row.last_name].filter(Boolean).join(' ') || 'Unknown Customer';
  const vehicle = [row.year, row.make, row.model].filter(Boolean).join(' ') || 'No vehicle selected';
  return {
    ...row,
    customer_name,
    vehicle,
    deal_type_label: labelDealType(row.deal_type),
    missing_docs: Number(row.missing_docs || 0),
    last_activity: row.last_activity || (row.closed_at ? 'Closed' : 'Deal started'),
  };
}

function logDeal(req, id, action, note) {
  db.prepare(`INSERT INTO activity_logs (dealership_id, entity_type, entity_id, action, note, user_id)
    VALUES (?, 'deal', ?, ?, ?, ?)`).run(req.user.dealership_id, id, action, note || null, req.user.id);
}

router.get('/', requireAuth, (req, res) => {
  const { status, q } = req.query;
  let sql = dealSelect();
  const params = [req.user.dealership_id];

  if (status && status !== 'all') {
    sql += ' AND d.status = ?';
    params.push(status);
  } else {
    sql += " AND d.status != 'dead'";
  }

  if (q) {
    sql += ` AND (
      c.first_name LIKE ? OR c.last_name LIKE ? OR c.email LIKE ? OR c.phone LIKE ?
      OR u.make LIKE ? OR u.model LIKE ? OR u.vin LIKE ?
    )`;
    const like = `%${q}%`;
    params.push(like, like, like, like, like, like, like);
  }

  sql += ` ORDER BY
    CASE WHEN d.next_follow_up_at IS NULL THEN 1 ELSE 0 END,
    d.next_follow_up_at ASC,
    d.created_at DESC`;

  const deals = db.prepare(sql).all(...params).map(enrichDeal);
  res.json({ deals });
});

router.get('/export/contacts.csv', requireAuth, (req, res) => {
  const rows = db.prepare(`
    SELECT DISTINCT
      COALESCE(c.first_name, '') AS first_name,
      COALESCE(c.last_name, '') AS last_name,
      COALESCE(c.email, '') AS email,
      COALESCE(c.phone, '') AS phone,
      COALESCE(d.status, '') AS deal_status,
      COALESCE(d.deal_type, '') AS deal_type
    FROM customers c
    LEFT JOIN deals d ON d.customer_id = c.id AND d.dealership_id = c.dealership_id
    WHERE c.dealership_id = ?
    ORDER BY c.last_name, c.first_name
  `).all(req.user.dealership_id);

  const escape = value => `"${String(value ?? '').replace(/"/g, '""')}"`;
  const csv = [
    ['First Name', 'Last Name', 'Email', 'Phone', 'Deal Status', 'Deal Type'].map(escape).join(','),
    ...rows.map(row => [row.first_name, row.last_name, row.email, row.phone, row.deal_status, row.deal_type].map(escape).join(',')),
  ].join('\n');

  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', 'attachment; filename="unit-navigator-contacts.csv"');
  res.send(csv);
});

router.post('/:id/email-reminder', requireAuth, (req, res) => {
  const deal = db.prepare(`${dealSelect()} AND d.id = ?`).get(req.user.dealership_id, req.params.id);
  if (!deal) return res.status(404).json({ error: 'Deal not found' });
  const enriched = enrichDeal(deal);
  const subject = `Deal follow-up: ${enriched.customer_name}`;
  const body = [
    `${enriched.customer_name} needs follow-up.`,
    `Vehicle: ${enriched.vehicle}`,
    `Deal type: ${enriched.deal_type_label}`,
    `Next follow-up: ${enriched.next_follow_up_at || 'Not set'}`,
    `Missing docs: ${enriched.missing_docs}`,
    '',
    'Generated by Unit Navigator.',
  ].join('\n');
  const mailto = `mailto:${encodeURIComponent(dealerEmail(req))}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

  logDeal(req, req.params.id, 'Reminder email prepared', `Mailto generated for ${dealerEmail(req)}`);
  res.json({
    ok: true,
    mailto,
    message: 'Email provider is not configured yet. Opening this link lets the dealer send the reminder from their mail app.',
  });
});

router.patch('/:id/status', requireAuth, (req, res) => {
  const { status } = req.body;
  if (!VALID_STATUSES.has(status)) return res.status(400).json({ error: 'Invalid deal status' });

  const deal = db.prepare('SELECT * FROM deals WHERE id = ? AND dealership_id = ?')
    .get(req.params.id, req.user.dealership_id);
  if (!deal) return res.status(404).json({ error: 'Deal not found' });

  const closedAt = status === 'closed' ? new Date().toISOString() : null;
  db.prepare('UPDATE deals SET status = ?, closed_at = ? WHERE id = ? AND dealership_id = ?')
    .run(status, closedAt, req.params.id, req.user.dealership_id);

  logDeal(req, req.params.id, 'Deal status changed', `${deal.status} -> ${status}`);
  const updated = db.prepare(`${dealSelect()} AND d.id = ?`).get(req.user.dealership_id, req.params.id);
  res.json({ deal: enrichDeal(updated) });
});

router.patch('/:id/follow-up', requireAuth, (req, res) => {
  const { next_follow_up_at } = req.body;
  const deal = db.prepare('SELECT * FROM deals WHERE id = ? AND dealership_id = ?')
    .get(req.params.id, req.user.dealership_id);
  if (!deal) return res.status(404).json({ error: 'Deal not found' });

  db.prepare('UPDATE deals SET next_follow_up_at = ? WHERE id = ? AND dealership_id = ?')
    .run(next_follow_up_at || null, req.params.id, req.user.dealership_id);

  logDeal(req, req.params.id, 'Follow-up changed', next_follow_up_at || 'Follow-up cleared');
  const updated = db.prepare(`${dealSelect()} AND d.id = ?`).get(req.user.dealership_id, req.params.id);
  res.json({ deal: enrichDeal(updated) });
});

router.delete('/:id', requireAuth, (req, res) => {
  const deal = db.prepare('SELECT * FROM deals WHERE id = ? AND dealership_id = ?')
    .get(req.params.id, req.user.dealership_id);
  if (!deal) return res.status(404).json({ error: 'Deal not found' });

  db.prepare('DELETE FROM documents WHERE deal_id = ? AND dealership_id = ?').run(req.params.id, req.user.dealership_id);
  db.prepare('DELETE FROM activity_logs WHERE entity_type = ? AND entity_id = ? AND dealership_id = ?')
    .run('deal', req.params.id, req.user.dealership_id);
  db.prepare('DELETE FROM deals WHERE id = ? AND dealership_id = ?').run(req.params.id, req.user.dealership_id);

  res.json({ ok: true });
});

module.exports = router;
